CREATE
  TABLE FORNECEDORES
  (
    CNPJ VARCHAR2 (20) NOT NULL ,
    NOME VARCHAR2 (50) NOT NULL ,
    EMAIL VARCHAR2 (30) NOT NULL ,
    ENDERECO VARCHAR2 (30) NOT NULL 
  ) ;
ALTER TABLE FORNECEDORES ADD CONSTRAINT FORNECEDORES_PK PRIMARY KEY (
CNPJ ) ;

CREATE 
   TABLE PROPOSTA
   (
      ID NUMBER (20) NOT NULL ,
      VENCEDORA VARCHAR2 (30) NOT NULL ,
      PRECO_OFERTADO FLOAT (126) NOT NULL ,
      CNPJ_FORNECEDOR VARCHAR2 (20) NOT NULL ,
      NUMERO_LICITACAO NUMBER (20) NOT NULL
   ) ;
ALTER TABLE PROPOSTA ADD CONSTRAINT PROPOSTA_FK FOREIGN KEY (
CNPJ_FORNECEDOR ) REFERENCES FORNECEDORES ( CNPJ ) ;
ALTER TABLE PROPOSTA ADD CONSTRAINT PROPOSTA_LICITACAOFK FOREIGN KEY ( NUMERO_LICITACAO ) REFERENCES LICITACAO ( NUMERO ) ;
ALTER TABLE PROPOSTA ADD CONSTRAINT PROPOSTA_PK PRIMARY KEY ( ID ) ;

CREATE 
   TABLE PRODUTO
   (
      CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL ,
      UNIDADE_MEDIDA VARCHAR2 (20) NOT NULL ,
      QUANTIDADE NUMBER (1000) NOT NULL ,
      VALOR_UNITARIO_MAXIMO FLOAT (126) NOT NULL ,
      NUMERO_LICITACAO NUMBER (30) NOT NULL ,
      ID_PROPOSTA NUMBER (30) NOT NULL ,
      NUMERO_PROCESSO NUMBER (30) NOT NULL ,
      CODIGO_ADITIVO NUMBER (30) NOT NULL
   ) ;
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_LICITACAOFK FOREIGN KEY ( NUMERO_LICITACAO ) REFERENCES LICITACAO ( NUMERO ) ;
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PROPOSTAFK FOREIGN KEY ( ID_PROPOSTA ) REFERENCES PROPOSTA ( ID );
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_CONTRATOFK FOREIGN KEY ( NUMERO_PROCESSO ) REFERENCES CONTRATO ( NUMERO_PROCESSO );
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_ADITIVOFK FOREIGN KEY ( CODIGO_ADITIVO ) REFERENCES ADITIVO ( CODIGO );
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PK PRIMARY KEY ( CODIGO_DE_BARRAS ) ;

CREATE 
   TABLE MODALIDADE
   (
     ID NUMBER (20,0) NOT NULL ,
     NOME VARCHAR2 (50) NOT NULL
   ) ;
ALTER TABLE MODALIDADE ADD CONSTRAINT MODALIDADE_PK PRIMARY KEY ( ID ) ;

CREATE SEQUENCE SEQ_MODALIDADE START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TRG_MODALIDADE BEFORE
  INSERT
    ON MODALIDADE FOR EACH ROW WHEN
    (
      NEW.ID IS NULL
    )
    BEGIN :NEW.ID := SEQ_MODALIDADE.NEXTVAL;
END;

CREATE 
   TABLE COMISSAO
   (
     ID NUMBER (20) NOT NULL 
   ) ;
ALTER TABLE COMISSAO ADD CONSTRAINT COMISSAO_PK PRIMARY KEY ( ID ) ;

CREATE 
   TABLE LICITACAO
   (
      NUMERO NUMBER (20) NOT NULL ,
      OBJETO VARCHAR2 (30) NOT NULL ,
      DATA_ABERTURA DATE NOT NULL ,
      EDITAL VARCHAR2 (50) NOT NULL ,
      ID_MODALIDADE NUMBER (20) NOT NULL ,
      ID_COMISSAO NUMBER (20) NOT NULL ,
      CODIGO_ORGAO NUMBER (20) NOT NULL
   ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_PK PRIMARY KEY ( NUMERO ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_MODALIDADEFK FOREIGN KEY (
ID_MODALIDADE ) REFERENCES MODALIDADE ( ID ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_COMISSAOFK FOREIGN KEY (
ID_COMISSAO ) REFERENCES COMISSAO ( ID ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_ORGAOFK FOREIGN KEY ( CODIGO_ORGAO ) REFERENCES ORGAO ( CODIGO );

CREATE 
   TABLE ADITIVO
   (
     CODIGO VARCHAR2 (20) NOT NULL ,
     MOTIVO VARCHAR2 (50) NOT NULL ,
     DATA_INICIO DATE (10) NOT NULL ,
     DATA_FIM DATE (10) NOT NULL ,
     VALOR FLOAT (126) NOT NULL ,
     NUMERO_PROCESSO NUMBER (40) NOT NULL
   ) ;
ALTER TABLE ADITIVO ADD CONSTRAINT ADITIVO_CONTRATOFK FOREIGN KEY ( NUMERO_PROCESSO  ) REFERENCES CONTRATO ( NUMERO_PROCESSO ) ;
ALTER TABLE ADITIVO ADD CONSTRAINT ADITIVO_PK PRIMARY KEY ( CODIGO ) ;

CREATE 
   TABLE ORGAO
   (
     CODIGO NUMBER (20) NOT NULL ,
     NOME VARCHAR2 (50) NOT NULL ,
     TELEFONE VARCHAR2 (20) NOT NULL ,
     EMAIL VARCHAR2 (50) NOT NULL ,
     ENDERECO VARCHAR2 (50) NOT NULL ,
     MATRICULA_FUNCIONARIO NUMBER (20) NOT NULL
   ) ;
ALTER TABLE ORGAO ADD CONSTRAINT ORGAO_PK PRIMARY KEY ( CODIGO ) ;
ALTER TABLE ORGAO ADD CONSTRAINT ORGAO_FK FOREIGN KEY ( MATRICULA_FUNCIONARIO ) REFERENCES FUNCIONARIO ( MATRICULA ) ;

CREATE 
   TABLE FUNCIONARIO
   (
     MATRICULA NUMBER (20) NOT NULL ,
     NOME VARCHAR2 (50) NOT NULL ,
     TELEFONE VARCHAR2 (20) NOT NULL ,
     EMAIL VARCHAR2 (50) NOT NULL ,
     CODIGO_ORGAO NUMBER (20) NOT NULL 
   ) ;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUNCIONARIO_PK PRIMARY KEY ( MATRICULA ) ;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUNCIONARIO_FK FOREIGN KEY ( CODIGO_ORGAO ) REFERENCES ORGAO ( CODIGO ) ;

CREATE 
   TABLE CONTRATO
   (
     VALOR_TOTAL FLOAT (126) NOT NULL ,
     OBJETO VARCHAR2 (50) NOT NULL ,
     DATA_INICIO DATE NOT NULL ,
     DATA_FIM VARCHAR2 NOT NULL ,
     NUMERO_PROCESSO NUMBER (40) NOT NULL  ,
     CNPJ_FORNECEDOR VARCHAR (20) NOT NULL ,
     NUMERO_LICITACAO NUMBER (30) NOT NULL
   ) ;
ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_FORNECEDORFK FOREIGN KEY ( CNPJ_FORNECEDOR ) REFERENCES FORNECEDORES ( CNPJ );
ALTER TABLE PRODUTO ADD CONSTRAINT CONTRATO_LICITACAOFK FOREIGN KEY ( NUMERO_LICITACAO ) REFERENCES LICITACAO ( NUMERO );
ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_PK PRIMARY KEY ( NUMERO_PROCESSO ) ;

-- Relações para Atributos Multivalorados --

CREATE 
   TABLE TELEFONESFORNECEDOR
   (
      NUMERO VARCHAR2 (20) NOT NULL ,
      CNPJ_FORNECEDOR VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE TELEFONESFORNECEDOR ADD CONSTRAINT TELEFONES_FK FOREIGN KEY (
CNPJ_FORNECEDOR ) REFERENCES FORNECEDORES ( CNPJ ) ;
ALTER TABLE TELEFONESFORNECEDOR ADD CONSTRAINT TELEFONES_PK PRIMARY KEY ( TELEFONES, CNPJ ) ;

-- Relações de Tipo N:M --

CREATE 
   TABLE PROPOSTAPRODUTO
   (
     ID_PROPOSTA NUMBER (20,0) NOT NULL ,
     CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE PROPOSTAPRODUTO ADD CONSTRAINT PROPOSTAPRODUTO_PRODUTOFK FOREIGN KEY (
CODIGO_DE_BARRAS ) REFERENCES PRODUTO ( CODIGO_DE_BARRAS ) ;
ALTER TABLE PROPOSTAPRODUTO ADD CONSTRAINT PROPOSTAPRODUTO_PROPOSTAFK FOREIGN KEY (
ID_PROPOSTA ) REFERENCES PROPOSTA ( ID ) ;
ALTER TABLE PROPOSTAPRODUTO ADD CONSTRAINT PROPOSTAPRODUTO_PK PRIMARY KEY ( ID, CODIGO_DE_BARRAS ) ;

CREATE 
   TABLE LICITACAOPRODUTO
   (
     CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL ,
     NUMERO_LICITACAO NUMBER (20) NOT NULL
   ) ;

ALTER TABLE LICITACAOPRODUTO ADD CONSTRAINT LICITACAOPRODUTO_PRODUTOFK FOREIGN KEY (
CODIGO_DE_BARRAS ) REFERENCES PRODUTO ( CODIGO_DE_BARRAS ) ;
ALTER TABLE LICITACAOPRODUTO ADD CONSTRAINT LICITACAOPRODUTO_LICITACAOFK FOREIGN KEY (
NUMERO_LICITACAO ) REFERENCES LICITACAO ( NUMERO ) ;
ALTER TABLE LICITACAOPRODUTO ADD CONSTRAINT LICITACAOCONTEMPRODUTO_PK PRIMARY KEY ( CODIGO_DE_BARRAS, NUMERO_LICITACAO ) ;

CREATE 
   TABLE ADITIVOPRODUTO
   (
     CODIGO VARCHAR2 (20) NOT NULL ,
     CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE ADITIVOPRODUTO ADD CONSTRAINT ADITIVOPRODUTO_PRODUTOFK FOREIGN KEY (
CODIGO_DE_BARRAS ) REFERENCES PRODUTO ( CODIGO_DE_BARRAS ) ;
ALTER TABLE ADITIVOPRODUTO ADD CONSTRAINT ADITIVOPRODUTO_ADITIVOFK FOREIGN KEY (
CODIGO ) REFERENCES ADITIVO ( CODIGO ) ;
ALTER TABLE ADITIVOPRODUTO ADD CONSTRAINT ADITIVOPRODUTO_PK PRIMARY KEY ( CODIGO , CODIGO_DE_BARRAS ) ;

CREATE 
   TABLE PRODUTOCONTRATO
   (
     NUMERO_PROCESSO VARCHAR2 (40) NOT NULL ,
     CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE PRODUTOCONTRATO ADD CONSTRAINT PRODUTOCONTRATO_CONTRATOFK FOREIGN KEY ( NUMERO_PROCESSO ) REFERENCES CONTRATO ( NUMERO_PROCESSO ) ;
ALTER TABLE PRODUTOCONTRATO ADD CONSTRAINT PRODUTOCONTRATO_PRODUTOFK FOREIGN KEY ( CODIGO_DE_BARRAS ) REFERENCES PRODUTO ( CODIGO_DE_BARRAS ) ;
ALTER TABLE PRODUTOCONTRATO ADD CONSTRAINT PRODUTOCONTRATO_PK PRIMARY KEY (NUMERO_PROCESSO , CODIGO_DE_BARRAS) ;

CREATE 
   TABLE FUNCIONARIOCOMISSAO
   (
     ID NUMBER (20) NOT NULL ,
     ID_COMISSAO NUMBER (20) NOT NULL ,
     MATRICULA_FUNCIONARIO NUMBER (20) NOT NULL
   ) ;
ALTER TABLE FUNCIONARIOCOMISSAO ADD CONSTRAINT FUNCIONARIOCOMISSAO_FUNCIONARIOFK FOREIGN KEY ( MATRICULA_FUNCIONARIO ) REFERENCES FUNCIONARIO ( MATRICULA ) ;
ALTER TABLE FUNCIONARIOCOMISSAO ADD CONSTRAINT FUNCIONARIOCOMISSAO_COMISSAOFK FOREIGN KEY ( ID_COMISSAO ) REFERENCES COMISSAO ( ID ) ;
ALTER TABLE FUNCIONARIOCOMISSAO ADD CONSTRAINT FUNCIONARIOCOMISSAO_PK PRIMARY KEY (ID , MATRICULA_FUNCIONARIO) ;

DROP TABLE FORNECEDORES CASCADE CONSTRAINTS;

DROP TABLE LICITACAO CASCADE CONSTRAINTS;

DROP TABLE TELEFONE CASCADE CONSTRAINTS;

DROP TABLE PROPOSTA CASCADE CONSTRAINTS;

DROP TABLE ADITIVO CASCADE CONSTRAINTS;

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

DROP TABLE MODALIDADE CASCADE CONSTRAINTS;

DROP TABLE COMISSAO CASCADE CONSTRAINTS;

DROP TABLE ORGAO CASCADE CONSTRAINTS;

DROP TABLE CONTRATO CASCADE CONSTRAINTS;

DROP TABLE LICITACAOPRODUTO CASCADE CONTRAINTS;

DROP TABLE PROPOSTAPRODUTO CASCADE CONTRAINTS;

DROP TABLE ADITIVOPRODUTO CASCADE CONTRAINTS;

DROP TABLE PRODUTOCONTRATO CASCADE CONTRAINTS;

DROP TABLE FUNCIONARIOCOMISSAO CASCADE CONTRAINTS;