CREATE
  TABLE FORNECEDORES
  (
    CNPJ VARCHAR2 (20) NOT NULL ,
    NOME VARCHAR2 (50) NOT NULL ,
    EMAIL VARCHAR2 (30) NOT NULL ,
    ENDERECO VARCHAR2 (30) NOT NULL 
  ) ;
ALTER TABLE FORNECEDORES ADD CONSTRAINT FORNECEDORES_PK PRIMARY KEY (
CNPJ ) ;

CREATE 
   TABLE TELEFONES
   (
      TELEFONES VARCHAR2 (20) NOT NULL,
      CNPJ VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE TELEFONES ADD CONSTRAINT FORNECEDORES_FK FOREIGN KEY (
CNPJ ) REFERENCES FORNECEDORES ( CNPJ ) ;

DROP TABLE FORNECEDORES CASCADE CONSTRAINTS;

DROP TABLE TELEFONE CASCADE CONSTRAINTS;