
CREATE
  TABLE FORNECEDORES
  (
    CNPJ VARCHAR2 (20) NOT NULL ,
    NOME VARCHAR2 (50) NOT NULL ,
    EMAIL VARCHAR2 (30) NOT NULL ,
    ENDERECO VARCHAR2 (30) NOT NULL 
  ) ;
ALTER TABLE FORNECEDORES ADD CONSTRAINT FORNECEDORES_PK PRIMARY KEY (
CNPJ ) ;

CREATE 
   TABLE TELEFONES
   (
      TELEFONES VARCHAR2 (20) NOT NULL ,
      CNPJ VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE TELEFONES ADD CONSTRAINT TELEFONES_FK FOREIGN KEY (
CNPJ ) REFERENCES FORNECEDORES ( CNPJ ) ;
ALTER TABLE TELEFONES ADD CONSTRAINT TELEFONES_PK PRIMARY KEY ( TELEFONES, CNPJ ) ;

CREATE 
   TABLE PROPOSTA
   (
      ID NUMBER (20,0) NOT NULL ,
      VENCEDORA VARCHAR2 (20) NOT NULL ,
      PRECO_OFERTADO FLOAT (126) NOT NULL ,
      CNPJ VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE PROPOSTA ADD CONSTRAINT PROPOSTA_FK FOREIGN KEY (
CNPJ ) REFERENCES FORNECEDORES ( CNPJ ) ;
ALTER TABLE TELEFONES ADD CONSTRAINT PROPOSTA_PK PRIMARY KEY ( ID ) ;

CREATE SEQUENCE SEQ_PROPOSTA START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TRG_PROPOSTA BEFORE
  INSERT
    ON PROPOSTA FOR EACH ROW WHEN
    (
      NEW.ID IS NULL
    )
    BEGIN :NEW.ID := SEQ_PROPOSTA.NEXTVAL;
END;

ALTER TRIGGER TRG_PROPOSTA;

CREATE 
   TABLE PRODUTO
   (
      CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL ,
      UNIDADE_MEDIDA VARCHAR2 (20) NOT NULL ,
      QUANTIDADE NUMBER (100) NOT NULL ,
      VALOR_UNITARIO_MAXIMO FLOAT (126) NOT NULL
   ) ;
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PK PRIMARY KEY ( CODIGO_DE_BARRAS ) ;

CREATE 
   TABLE PROPOSTACONTEMPRODUTO
   (
     ID NUMBER (20,0) NOT NULL ,
     CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL
   ) ;
ALTER TABLE PROPOSTACONTEMPRODUTO ADD CONSTRAINT PROPOSTACONTEMPRODUTO_PK PRIMARY KEY ( ID, CODIGO_DE_BARRAS ) ;

CREATE 
   TABLE MODALIDADE
   (
     ID NUMBER (20,0) NOT NULL ,
     NOME VARCHAR2 (50) NOT NULL
   ) ;
ALTER TABLE MODALIDADE ADD CONSTRAINT MODALIDADE_PK PRIMARY KEY ( ID ) ;

CREATE SEQUENCE SEQ_MODALIDADE START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TRG_MODALIDADE BEFORE
  INSERT
    ON MODALIDADE FOR EACH ROW WHEN
    (
      NEW.ID IS NULL
    )
    BEGIN :NEW.ID := SEQ_MODALIDADE.NEXTVAL;
END;

CREATE 
   TABLE COMISSAO
   (
     ID NUMBER (20,0) NOT NULL 
   ) ;
ALTER TABLE COMISSAO ADD CONSTRAINT COMISSAO_PK PRIMARY KEY ( ID ) ;

CREATE SEQUENCE SEQ_COMISSAO START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TRG_COMISSAO BEFORE
  INSERT
    ON COMISSAO FOR EACH ROW WHEN
    (
      NEW.ID IS NULL
    )
    BEGIN :NEW.ID := SEQ_COMISSAO.NEXTVAL;
END;

ALTER TRIGGER TRG_COMISSAO;

CREATE 
   TABLE LICITACAO
   (
      NUMERO NUMBER (20) NOT NULL ,
      OBJETO VARCHAR2 (30) NOT NULL ,
      DATA_ABERTURA DATE NOT NULL ,
      EDITAL VARCHAR2 (50) NOT NULL ,
      ID_MODALIDADE NUMBER (20,0) NOT NULL ,
      ID_COMISSAO NUMBER (20,0) NOT NULL 
   ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_PK PRIMARY KEY ( NUMERO ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_FK FOREIGN KEY (
ID_MODALIDADE ) REFERENCES MODALIDADE ( ID ) ;
ALTER TABLE LICITACAO ADD CONSTRAINT LICITACAO_FK FOREIGN KEY (
ID_COMISSAO ) REFERENCES COMISSAO ( ID ) ;

CREATE 
   TABLE LICITACAOCONTEMPRODUTO
   (
     CODIGO_DE_BARRAS VARCHAR2 (20) NOT NULL ,
     NUMERO NUMBER (20) NOT NULL
   ) ;
ALTER TABLE LICITACAOCONTEMPRODUTO ADD CONSTRAINT LICITACAOCONTEMPRODUTO_PK PRIMARY KEY ( CODIGO_DE_BARRAS, NUMERO ) ;

DROP TABLE FORNECEDORES CASCADE CONSTRAINTS;

DROP TABLE TELEFONE CASCADE CONSTRAINTS;

DROP TABLE PROPOSTA CASCADE CONSTRAINTS;

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

DROP TABLE PROPOSTACONTEMPRODUTO CASCADE CONSTRAINTS;

DROP TABLE LICITACAO CASCADE CONSTRAINTS;

DROP TABLE LICITACAOCONTEMPRODUTO CASCADE CONSTRAINTS;

DROP TABLE MODALIDADE CASCADE CONSTRAINTS;

DROP TABLE COMISSAO CASCADE CONSTRAINTS;