/* Grupo 5 - Banco de Dados I
 
Alunos:
 
- Davyson Douglas Gomes Guimarães - 119210872.
- Henrique Dias Oliveira de Nóbrega - 120210069.
- José Artur Procopio Coelho - 120210625.
- Lucas Riberio Agra Alexandre - 119210120.
- Paulo Victor Machado de Souza - 120110398.
- Victor Alexandre Cavalcanti Macedo - 120210046.
 
*/

-- Questão 1

SELECT CODCLI FROM CLIENTE WHERE CODCLI IN (
SELECT CODIGO_CLIENTE FROM ORDEM_DE_COMPRA WHERE CODORDEM IN ( SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO WHERE
CODIGO_PRODUTO IN (
SELECT CODPROD FROM PRODUTO WHERE COD_CATEGORIA IN ( SELECT CODCAT FROM CATEGORIA WHERE NOME = 'Queijos')
)
)
) MINUS
SELECT CODCLI FROM CLIENTE WHERE CODCLI IN (
SELECT CODIGO_CLIENTE FROM ORDEM_DE_COMPRA WHERE CODORDEM IN ( SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO WHERE
CODIGO_PRODUTO IN (
SELECT CODPROD FROM PRODUTO WHERE COD_CATEGORIA IN ( SELECT CODCAT FROM CATEGORIA WHERE NOME = 'bebida')
)
)
)

-- Questão 2

SELECT * FROM CLIENTE WHERE CLIENTE_INDICA IN ( SELECT CODCLI FROM CLIENTE WHERE NOME = 'Jose Reis'
)AND CODCLI NOT IN (SELECT CODIGO_CLIENTE FROM ORDEM_DE_COMPRA WHERE CODORDEM IN (
SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO)) AND DATA_INDICACAO < '07/21/2019'


-- Questão 3 
SELECT EXTRACT(MONTH FROM DATA_COMPRA) AS MES_COMPRA, EXTRACT(YEAR FROM DATA_COMPRA) AS ANO_COMPRA,
COUNT(*) AS TOTAL_COMPRAS FROM ORDEM_DE_COMPRA WHERE STATUS = 'FINALIZADA' GROUP BY
EXTRACT(MONTH FROM DATA_COMPRA), EXTRACT(YEAR FROM DATA_COMPRA)

-- Questão 4

SELECT NOME,COUNT(*) AS COMPRAS FROM CLIENTE,ORDEM_DE_COMPRA WHERE CODORDEM IN (
SELECT CODORDEM FROM ORDEM_DE_COMPRA WHERE CODIGO_TRANSPORTADORA IN (
SELECT CODTRANS FROM TRANSPORTADORA WHERE NOME = 'Full
Entregas'AND CODORDEM IN(
SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO))AND CODCLI = CODIGO_CLIENTE)GROUP BY NOME

-- Questão 5

SELECT END_CIDADE FROM(
SELECT END_CIDADE,MAX(SOMA_QUANTIDADE) FROM(
SELECT END_CIDADE,SUM(QUANTIDADE) AS SOMA_QUANTIDADE FROM ORDEM_DE_COMPRA,COMPRA_PRODUTO WHERE CODORDEM IN
(SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO WHERE CODIGO_PRODUTO IN
(SELECT CODPROD FROM PRODUTO WHERE COD_CATEGORIA IN (SELECT CODCAT FROM CATEGORIA WHERE NOME = 'Smartphone'))) AND
CODORDEM = CODIGO_COMPRA GROUP BY END_CIDADE
) GROUP BY END_CIDADE ORDER BY MAX(SOMA_QUANTIDADE) DESC
) WHERE ROWNUM = 1

-- Questão 6

SELECT * FROM CLIENTE WHERE DATA_NASCIMENTO < '12/31/1999' AND CODCLI NOT IN (
SELECT CODIGO_CLIENTE FROM ORDEM_DE_COMPRA WHERE CODORDEM IN ( SELECT CODIGO_COMPRA FROM COMPRA_AVALIA_PRODUTO)
) AND CODCLI IN (SELECT CODIGO_CLIENTE FROM ORDEM_DE_COMPRA WHERE CODORDEM IN (
SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO))

-- Questão 7

SELECT * FROM ORDEM_DE_COMPRA WHERE DESCONTO >= 300 AND STATUS =
'Em Separação.'
 
-- Questão 8

SELECT AVG(QUANTIDADE) AS MEDIA_VENDAS_MES FROM(
SELECT EXTRACT(MONTH FROM DATA_COMPRA)AS MES ,COUNT(*) AS QUANTIDADE FROM ORDEM_DE_COMPRA WHERE CODORDEM IN (
SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO WHERE CODIGO_PRODUTO IN (
SELECT CODPROD FROM PRODUTO WHERE COD_CATEGORIA IN ( SELECT CODCAT FROM CATEGORIA WHERE NOME = 'Smartphone')
)) GROUP BY EXTRACT(MONTH FROM DATA_COMPRA)
)

-- Questão 9

SELECT END_CIDADE,MEDIA_FRETE FROM(SELECT END_CIDADE,AVG(VALOR_FRETE) AS MEDIA_FRETE FROM ORDEM_DE_COMPRA GROUP BY END_CIDADE ) WHERE MEDIA_FRETE < 43

-- Questão 10

SELECT DISTINCT NOME,CNPJ FROM FORNECEDOR WHERE CODFORN IN( SELECT CODIGO_FORNECEDOR FROM FORNECIMENTO WHERE
CODIGO_PRODUTO IN(
SELECT CODPROD FROM PRODUTO WHERE COD_CATEGORIA IN ( SELECT CODCAT FROM CATEGORIA WHERE NOME = 'Queijos' OR NOME !=
'Laticínios')
)
)

-- Questão 11

SELECT END_CIDADE,VALOR FROM(
SELECT END_CIDADE,SUM(VALOR_ATUAL) AS VALOR FROM ORDEM_DE_COMPRA,COMPRA_PRODUTO WHERE CODORDEM IN
(SELECT CODIGO_COMPRA FROM COMPRA_PRODUTO ) AND CODORDEM = CODIGO_COMPRA AND EXTRACT(MONTH FROM DATA_COMPRA) = 3 GROUP BY END_CIDADE
) WHERE VALOR < 61000
